---

- name: Create Azure Storage Account
  azure_rm_storageaccount:
    resource_group: "{{ rg_name }}"
    name: "{{ sa_name }}"
    type: "{{ sa_type }}"
    subscription_id: "{{ subscription_id | default(omit) }}"
    tenant: "{{ tenant | default(omit) }}"
    client_id: "{{ client_id | default(omit) }}"
    secret: "{{ secret | default(omit) }}"